-- ============================================================
-- SMART TRAVEL PLANNER — COMPLETE SEED DATA
-- Merges: india_destinations.sql + sample_data.sql
-- ============================================================
-- Run AFTER database_schema.sql AND after starting the app once
-- (the app auto-creates the admin user on first startup).
--
--   Step 1:  mysql -u root -p < database/database_schema.sql
--   Step 2:  mvn spring-boot:run   (wait for "Started SmartTravelApp")
--   Step 3:  Ctrl+C to stop
--   Step 4:  mysql -u root smart_travel_db < database/seed_data.sql
--   Step 5:  mvn spring-boot:run   (run normally)
-- ============================================================

USE smart_travel_db;

-- ============================================================
-- DESTINATIONS
-- India (IDs 1–30) then Global (IDs 31–40)
-- ============================================================

-- India destinations
INSERT INTO destinations (name, country, description, temperature_avg, best_time_to_visit, currency, language, latitude, longitude, travel_type, budget_category, average_rating, review_count, image_url) VALUES
('Agra - Taj Mahal',              'India', 'Home to the iconic Taj Mahal, one of the Seven Wonders of the World. Agra is a city steeped in Mughal history with magnificent forts and palaces.',                                                        25, 'October to March',                              'INR', 'Hindi',              27.1767, 78.0081, 'Cultural',   'MidRange', 4.8, 0, 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600'),
('Goa',                           'India', 'India''s beach paradise with golden shores, turquoise waters, vibrant nightlife, and a unique blend of Indian and Portuguese culture.',                                                                    27, 'November to February',                          'INR', 'Konkani, English',   15.2993, 74.1240, 'Beach',      'Budget',   4.6, 0, 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600'),
('Jaipur - Pink City',            'India', 'The Pink City of Rajasthan famous for Hawa Mahal, Amer Fort, and City Palace. A stunning blend of royal heritage and vibrant bazaars.',                                                                    25, 'October to March',                              'INR', 'Hindi, Rajasthani',  26.9124, 75.7873, 'Cultural',   'MidRange', 4.7, 0, 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=600'),
('Kerala Backwaters',             'India', 'A serene network of lagoons, lakes, and canals in God''s Own Country. Houseboat cruises through lush paddy fields and coconut groves are unmissable.',                                                     27, 'September to March',                            'INR', 'Malayalam',          9.4981,  76.3388, 'Nature',     'MidRange', 4.7, 0, 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600'),
('Varanasi',                      'India', 'One of the world''s oldest living cities on the banks of the Ganges. Experience spiritual rituals, ancient ghats, and the eternal cycle of life and death.',                                               24, 'October to March',                              'INR', 'Hindi',              25.3176, 82.9739, 'Cultural',   'Budget',   4.5, 0, 'https://images.unsplash.com/photo-1561361513-2d8efce50688?w=600'),
('Leh Ladakh',                    'India', 'High-altitude desert landscape with ancient monasteries, turquoise lakes, and dramatic mountain passes. A dream for adventure seekers and motorcyclists.',                                                   5,  'June to September',                             'INR', 'Ladakhi, Hindi',     34.1526, 77.5771, 'Adventure',  'MidRange', 4.9, 0, 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600'),
('Rishikesh',                     'India', 'The Yoga Capital of the World situated on the banks of the Ganges. Famous for white-water rafting, bungee jumping, yoga retreats, and spiritual ashrams.',                                                  20, 'February to May, September to November',        'INR', 'Hindi',              30.0869, 78.2676, 'Adventure',  'Budget',   4.6, 0, 'https://images.unsplash.com/photo-1600100397608-c13e3e23e3c7?w=600'),
('Shimla',                        'India', 'The Queen of Hill Stations in the Himalayas, former summer capital of British India. Charming colonial architecture, scenic toy trains, and snow-capped views.',                                             12, 'March to June, December to February (snow)',    'INR', 'Hindi',              31.1048, 77.1734, 'Mountain',   'MidRange', 4.5, 0, 'https://images.unsplash.com/photo-1573158754104-b7e2b2430eca?w=600'),
('Udaipur - City of Lakes',       'India', 'The most romantic city in India, surrounded by Aravalli hills and glittering lakes. Magnificent palaces, ornate temples, and lakeside heritage hotels.',                                                    24, 'October to March',                              'INR', 'Hindi, Rajasthani',  24.5854, 73.7125, 'Cultural',   'Luxury',   4.8, 0, 'https://images.unsplash.com/photo-1598091383021-15ddea10925d?w=600'),
('Manali',                        'India', 'A high-altitude Himalayan resort town famous for adventure sports, snow peaks, ancient temples, and the gateway to Rohtang Pass and Spiti Valley.',                                                          8,  'October to June (snow), July to September (adventure)', 'INR', 'Hindi, Kullu', 32.2396, 77.1887, 'Mountain', 'MidRange', 4.6, 0, 'https://images.unsplash.com/photo-1580289144113-4b8a35a1c09a?w=600'),
('Darjeeling',                    'India', 'The Land of the Thunderbolt with sweeping views of Kanchenjunga, famous tea plantations, the Darjeeling Himalayan Railway (UNESCO), and colonial charm.',                                                  12, 'March to May, September to November',           'INR', 'Bengali, Nepali',    27.0410, 88.2663, 'Mountain',   'Budget',   4.5, 0, 'https://images.unsplash.com/photo-1623943491053-4a2c4f89f7d0?w=600'),
('Hampi',                         'India', 'A UNESCO World Heritage Site and the ruins of the Vijayanagara Empire. Boulder-strewn landscape with stunning temples, bazaars, and chariot streets.',                                                      27, 'October to February',                           'INR', 'Kannada',            15.3350, 76.4600, 'Cultural',   'Budget',   4.7, 0, 'https://images.unsplash.com/photo-1600697230053-c3e4ef7e0b73?w=600'),
('Andaman Islands',               'India', 'Pristine tropical islands in the Bay of Bengal with white sandy beaches, coral reefs, and crystal-clear waters perfect for snorkeling and scuba diving.',                                                   26, 'October to May',                                'INR', 'Hindi, Bengali',     11.7401, 92.6586, 'Beach',      'MidRange', 4.8, 0, 'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=600'),
('Munnar',                        'India', 'A misty hill station in Kerala blanketed by rolling tea plantations, spice gardens, and lush forests. Home to the rare Neelakurinji flower.',                                                              15, 'September to March',                            'INR', 'Malayalam',          10.0889, 77.0595, 'Nature',     'MidRange', 4.6, 0, 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600'),
('Mysore',                        'India', 'The City of Palaces in Karnataka, famous for the stunning Mysore Palace, Chamundi Hills, silk sarees, and the grand Dasara celebrations.',                                                                  25, 'October to February',                           'INR', 'Kannada',            12.2958, 76.6394, 'Cultural',   'MidRange', 4.5, 0, 'https://images.unsplash.com/photo-1571536802807-30451e3955d8?w=600'),
('Coorg',                         'India', 'Scotland of India nestled in the Western Ghats. Lush coffee and spice plantations, misty hills, waterfalls, and vibrant Kodava culture.',                                                                   20, 'October to March',                              'INR', 'Kodava, Kannada',    12.3375, 75.8069, 'Nature',     'MidRange', 4.6, 0, 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=600'),
('Ooty',                          'India', 'The Queen of Hill Stations in Tamil Nadu with tea gardens, botanical gardens, and the scenic Nilgiri Mountain Railway. Perfect escape from summer heat.',                                                   15, 'April to June, September to November',          'INR', 'Tamil',              11.4102, 76.6950, 'Mountain',   'Budget',   4.4, 0, 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=600'),
('Ranthambore National Park',     'India', 'One of India''s best wildlife sanctuaries, famous for its Bengal tiger population. Historic Ranthambore Fort within the park adds to its mystique.',                                                        25, 'October to June',                               'INR', 'Hindi, Rajasthani',  26.0173, 76.5026, 'Nature',     'MidRange', 4.7, 0, 'https://images.unsplash.com/photo-1602491453631-e2a5ad90a131?w=600'),
('Pondicherry',                   'India', 'A former French colony with charming colonial architecture, tranquil ashrams, pristine beaches, and a unique blend of French and Tamil cultures.',                                                           28, 'October to March',                              'INR', 'Tamil, French',      11.9416, 79.8083, 'Beach',      'Budget',   4.4, 0, 'https://images.unsplash.com/photo-1582531865817-b8bb4c9e1e1f?w=600'),
('Mahabalipuram',                 'India', 'UNESCO World Heritage coastal town known for its 7th-century rock-cut temples, Shore Temple, and the famous Descent of the Ganges bas-relief.',                                                             28, 'October to March',                              'INR', 'Tamil',              12.6269, 80.1927, 'Cultural',   'Budget',   4.4, 0, 'https://images.unsplash.com/photo-1609512601671-dc2e1b80bbb6?w=600'),
('Kolkata',                       'India', 'The City of Joy and cultural capital of India. Victoria Memorial, Howrah Bridge, colonial architecture, intellectual heritage, and amazing street food.',                                                    26, 'October to March',                              'INR', 'Bengali',            22.5726, 88.3639, 'Cultural',   'Budget',   4.3, 0, 'https://images.unsplash.com/photo-1558431382-27e303142255?w=600'),
('Mumbai',                        'India', 'The Maximum City and financial capital of India. Gateway of India, Marine Drive, Bollywood, street food, and the perfect blend of old and modern.',                                                          27, 'November to February',                          'INR', 'Hindi, Marathi',     19.0760, 72.8777, 'Cultural',   'MidRange', 4.5, 0, 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=600'),
('Delhi',                         'India', 'India''s capital with incredible Mughal monuments including Red Fort, Qutub Minar, Humayun''s Tomb, vibrant markets, and world-class dining.',                                                             24, 'October to March',                              'INR', 'Hindi',              28.7041, 77.1025, 'Cultural',   'MidRange', 4.4, 0, 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=600'),
('Jaisalmer - Golden City',       'India', 'The Golden City rising from the Thar Desert with a magnificent sandstone fort, ornate havelis, and magical camel safaris under starry skies.',                                                              28, 'October to February',                           'INR', 'Hindi, Rajasthani',  26.9157, 70.9083, 'Adventure',  'MidRange', 4.7, 0, 'https://images.unsplash.com/photo-1604608672516-5b9a8e6b3d3d?w=600'),
('Amritsar',                      'India', 'Home to the magnificent Golden Temple, the holiest shrine of Sikhism. The Wagah Border ceremony and Jallianwala Bagh add historical depth.',                                                                22, 'October to March',                              'INR', 'Punjabi, Hindi',     31.6340, 74.8723, 'Cultural',   'Budget',   4.7, 0, 'https://images.unsplash.com/photo-1609952542840-df54cfdefa2d?w=600'),
('Spiti Valley',                  'India', 'A remote cold desert mountain valley in the Himalayas. Ancient Buddhist monasteries, barren landscapes, and star-studded skies make it unique.',                                                             2,  'June to October',                               'INR', 'Spitian, Hindi',     32.2461, 78.0322, 'Adventure',  'Budget',   4.8, 0, 'https://images.unsplash.com/photo-1566837486754-44a6d7c16b58?w=600'),
('Pushkar',                       'India', 'A sacred city in Rajasthan built around the holy Pushkar Lake. Famous for the world''s only Brahma temple and the largest camel fair on earth.',                                                            25, 'October to March',                              'INR', 'Hindi, Rajasthani',  26.4899, 74.5511, 'Cultural',   'Budget',   4.4, 0, 'https://images.unsplash.com/photo-1598091383021-15ddea10925d?w=600'),
('Hyderabad',                     'India', 'The City of Pearls and Nizams with magnificent Charminar, Golconda Fort, legendary biryani, and a booming IT sector meeting ancient culture.',                                                              27, 'October to February',                           'INR', 'Telugu, Urdu',       17.3850, 78.4867, 'Cultural',   'MidRange', 4.4, 0, 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=600'),
('Alleppey - Venice of the East', 'India', 'The Venice of the East with extensive canal networks, charming houseboats drifting through emerald backwaters, and beautiful beaches.',                                                                     27, 'November to February',                          'INR', 'Malayalam',          9.4981,  76.3388, 'Nature',     'Budget',   4.6, 0, 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600'),
('Jim Corbett National Park',     'India', 'India''s oldest national park in the Himalayan foothills, famous for Bengal tigers, Asian elephants, leopards, and rich birdlife amid dense forests.',                                                     20, 'November to June',                              'INR', 'Hindi',              29.5300, 78.7747, 'Nature',     'MidRange', 4.6, 0, 'https://images.unsplash.com/photo-1561715276-a2d087060f1d?w=600');

-- Global destinations (IDs 31–40)
INSERT INTO destinations (name, country, description, temperature_avg, best_time_to_visit, currency, language, latitude, longitude, travel_type, budget_category, average_rating, review_count, image_url) VALUES
('Paris',        'France',      'The City of Light, famous for the Eiffel Tower, world-class museums, and romantic atmosphere.',                                         12, 'April to June, September to October',                    'EUR', 'French',                    48.8566,  2.3522,   'Cultural',  'Luxury',   4.7, 0, 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600'),
('Tokyo',        'Japan',       'Vibrant metropolis blending tradition and modernity with temples, zen gardens, and bustling neon-lit streets.',                          16, 'March to May, September to November',                    'JPY', 'Japanese',                  35.6762,  139.6503, 'Cultural',  'MidRange', 4.8, 0, 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600'),
('New York',     'USA',         'The city that never sleeps with iconic skyscrapers, world-class museums, Broadway shows, and incredible diverse culture.',               12, 'April to June, September to October',                    'USD', 'English',                   40.7128,  -74.0060, 'Adventure', 'Luxury',   4.5, 0, 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=600'),
('Bali',         'Indonesia',   'Tropical paradise with beautiful beaches, lush rice terraces, ancient temples, and vibrant adventure activities.',                       28, 'April to June, September to October',                    'IDR', 'Indonesian',                -8.6705,  115.2126, 'Beach',     'Budget',   4.6, 0, 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600'),
('Swiss Alps',   'Switzerland', 'Stunning mountain scenery with pristine glaciers, charming villages, and world-class skiing. Perfect for summer hiking too.',             5, 'June to September (summer), December to March (winter)', 'CHF', 'German, French, Italian',   46.8182,  8.2275,   'Adventure', 'Luxury',   4.9, 0, 'https://images.unsplash.com/photo-1531400158697-004b4b9f5bc1?w=600'),
('Bangkok',      'Thailand',    'Bustling capital with gilded temples, vibrant floating markets, world-famous street food, and electrifying nightlife.',                   27, 'November to February',                                   'THB', 'Thai',                      13.7563,  100.5018, 'Cultural',  'Budget',   4.4, 0, 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=600'),
('Barcelona',    'Spain',       'Coastal city renowned for Gaudí masterpieces, lively Las Ramblas, golden beaches, and delectable Catalan cuisine.',                      14, 'April to June, September to October',                    'EUR', 'Catalan, Spanish',          41.3851,  2.1734,   'Cultural',  'MidRange', 4.5, 0, 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=600'),
('Maldives',     'Maldives',    'Exclusive island paradise with overwater bungalows, crystal-clear lagoons, vibrant coral reefs, and absolute luxury seclusion.',          28, 'November to April',                                      'MVR', 'Dhivehi',                   4.1694,   73.5090,  'Beach',     'Luxury',   4.9, 0, 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=600'),
('Machu Picchu', 'Peru',        'Ancient Inca citadel perched high in the Andes, surrounded by mist and dramatic peaks — one of the world''s great wonders.',             12, 'May to October',                                         'PEN', 'Spanish, Quechua',          -13.1631, -72.5450, 'Nature',    'Budget',   4.8, 0, 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=600'),
('Iceland',      'Iceland',     'Land of fire and ice featuring dramatic waterfalls, erupting geysers, vast glaciers, and the magical Northern Lights.',                   0, 'June to August (midnight sun), Sep to Mar (Aurora)',     'ISK', 'Icelandic',                 64.9631,  -19.0208, 'Adventure', 'Luxury',   4.7, 0, 'https://images.unsplash.com/photo-1490077476659-095159692ab5?w=600');

-- ============================================================
-- HOTELS  (destination_id 31=Paris, 32=Tokyo, 34=Bali)
-- ============================================================

-- Paris hotels (destination_id = 31)
INSERT INTO hotels (destination_id, name, description, address, check_in_time, check_out_time, star_rating, price_per_night, currency, room_types, amenities, average_rating, available_rooms, image_url) VALUES
(31, 'Eiffel Tower Hotel',      'Luxury 5-star hotel a short walk from the Eiffel Tower',          '123 Avenue de la Tour, Paris',         '15:00', '11:00', 5, 350.00, 'EUR', 'Single,Double,Suite',  'WiFi,Pool,Gym,Restaurant,Spa,Parking',         4.8, 15, 'https://images.unsplash.com/photo-1551882547-ff40c4fe799f?w=600'),
(31, 'Marais Boutique',         'Charming 4-star boutique hotel in the historic Marais district',  '45 Rue des Rosiers, Paris',            '15:00', '11:00', 4, 200.00, 'EUR', 'Double,Suite',          'WiFi,Restaurant,AC',                           4.5, 20, 'https://images.unsplash.com/photo-1551882547-ff40c4fe799f?w=600'),
(31, 'Budget Paris Inn',        'Affordable 3-star hotel with clean rooms and basic amenities',    '789 Rue de la Paix, Paris',            '14:00', '10:00', 3,  80.00, 'EUR', 'Single,Double',         'WiFi,AC',                                      4.0, 25, 'https://images.unsplash.com/photo-1551882547-ff40c4fe799f?w=600'),
(31, 'Seine River Mansion',     'Elegant 4-star hotel overlooking the Seine River',                '321 Quai de la Seine, Paris',          '15:00', '11:00', 4, 220.00, 'EUR', 'Double,Suite,Deluxe',   'WiFi,Restaurant,Gym,Parking',                  4.6, 18, 'https://images.unsplash.com/photo-1551882547-ff40c4fe799f?w=600'),
(31, 'Latin Quarter Lodge',     '3-star hotel in the vibrant Latin Quarter',                       '456 Rue Mouffetard, Paris',            '14:00', '10:00', 3,  95.00, 'EUR', 'Single,Double',         'WiFi,AC,TV',                                   4.2, 22, 'https://images.unsplash.com/photo-1551882547-ff40c4fe799f?w=600'),
(31, 'Champs-Élysées Palace',   '5-star luxury hotel on the famous Champs-Élysées',               '789 Avenue des Champs-Élysées, Paris', '15:00', '11:00', 5, 400.00, 'EUR', 'Suite,Deluxe',          'WiFi,Pool,Gym,Restaurant,Spa,Parking,TV',      4.9, 12, 'https://images.unsplash.com/photo-1551882547-ff40c4fe799f?w=600'),
(31, 'Montmartre Retreat',      '4-star hotel in the artistic Montmartre neighbourhood',           '234 Rue Lepic, Paris',                 '15:00', '11:00', 4, 180.00, 'EUR', 'Double,Suite',          'WiFi,Restaurant,AC',                           4.4, 21, 'https://images.unsplash.com/photo-1551882547-ff40c4fe799f?w=600'),
(31, 'Le Marais Express',       '2-star budget hotel with clean, comfortable rooms',               '567 Rue Saint-Antoine, Paris',         '13:00', '10:00', 2,  60.00, 'EUR', 'Single,Double',         'WiFi',                                         3.8, 30, 'https://images.unsplash.com/photo-1551882547-ff40c4fe799f?w=600'),
(31, 'Versailles Grand',        '5-star palace-style hotel near Versailles',                       '111 Boulevard de Versailles, Paris',   '15:00', '11:00', 5, 380.00, 'EUR', 'Suite,Deluxe',          'WiFi,Pool,Gym,Restaurant,Spa,Parking',         4.7, 14, 'https://images.unsplash.com/photo-1551882547-ff40c4fe799f?w=600'),
(31, 'Notre-Dame View Hotel',   '4-star hotel with direct views of Notre-Dame Cathedral',          '654 Rue de Rivoli, Paris',             '15:00', '11:00', 4, 210.00, 'EUR', 'Double,Suite',          'WiFi,Restaurant,AC,Parking',                   4.5, 19, 'https://images.unsplash.com/photo-1551882547-ff40c4fe799f?w=600'),
(31, 'Arc de Triomphe Suite',   '3-star hotel a short stroll from Arc de Triomphe',               '876 Avenue Kleber, Paris',             '14:00', '10:00', 3, 110.00, 'EUR', 'Double,Suite',          'WiFi,AC,TV,Restaurant',                        4.3, 23, 'https://images.unsplash.com/photo-1551882547-ff40c4fe799f?w=600'),
(31, 'Louvre District Inn',     '4-star hotel steps away from the Louvre Museum',                  '345 Rue de Rivoli, Paris',             '15:00', '11:00', 4, 190.00, 'EUR', 'Double,Suite',          'WiFi,Restaurant,Gym,AC',                       4.4, 20, 'https://images.unsplash.com/photo-1551882547-ff40c4fe799f?w=600');

-- Tokyo hotels (destination_id = 32)
INSERT INTO hotels (destination_id, name, description, address, check_in_time, check_out_time, star_rating, price_per_night, currency, room_types, amenities, average_rating, available_rooms, image_url) VALUES
(32, 'Shinjuku Palace Hotel',   'Luxury 5-star hotel in the heart of Shinjuku',                   '1-1 Shinjuku, Tokyo',   '15:00', '11:00', 5, 280.00, 'JPY', 'Single,Double,Suite', 'WiFi,Pool,Gym,Restaurant,Spa',             4.8, 12, 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=600'),
(32, 'Shibuya Modern',          '4-star contemporary hotel in the Shibuya crossing district',     '2-1 Shibuya, Tokyo',    '15:00', '11:00', 4, 180.00, 'JPY', 'Double,Suite',        'WiFi,Restaurant,AC',                       4.5, 18, 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=600'),
(32, 'Asakusa Heritage',        '3-star traditional hotel near the iconic Senso-ji Temple',       '3-1 Asakusa, Tokyo',    '14:00', '10:00', 3,  85.00, 'JPY', 'Single,Double',       'WiFi,AC',                                  4.2, 24, 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=600'),
(32, 'Ginza Luxury Suites',     '5-star premium hotel in the upscale Ginza shopping district',   '4-1 Ginza, Tokyo',      '15:00', '11:00', 5, 320.00, 'JPY', 'Suite,Deluxe',        'WiFi,Pool,Gym,Restaurant,Spa,Parking',     4.9, 10, 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=600'),
(32, 'Harajuku Youth Hostel',   '2-star budget hostel popular with backpackers near Harajuku',   '5-1 Harajuku, Tokyo',   '13:00', '10:00', 2,  50.00, 'JPY', 'Single,Double',       'WiFi',                                     3.9, 28, 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=600'),
(32, 'Ikebukuro Comfort',       '4-star mid-range hotel in the lively Ikebukuro district',       '6-1 Ikebukuro, Tokyo',  '15:00', '11:00', 4, 170.00, 'JPY', 'Double,Suite',        'WiFi,Restaurant,AC',                       4.4, 20, 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=600'),
(32, 'Tokyo Tower View',        '3-star hotel with panoramic views of Tokyo Tower',               '7-1 Minato, Tokyo',     '14:00', '10:00', 3,  95.00, 'JPY', 'Double,Suite',        'WiFi,AC,Restaurant',                       4.3, 22, 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=600'),
(32, 'Ueno Park Hotel',         '4-star hotel nestled beside Ueno Park and its museums',          '8-1 Ueno, Tokyo',       '15:00', '11:00', 4, 190.00, 'JPY', 'Double,Suite',        'WiFi,Gym,Restaurant,Parking',              4.5, 19, 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=600'),
(32, 'Roppongi Sky Hotel',      '5-star luxury hotel in the cosmopolitan Roppongi district',     '9-1 Roppongi, Tokyo',   '15:00', '11:00', 5, 300.00, 'JPY', 'Suite,Deluxe',        'WiFi,Pool,Gym,Restaurant,Spa',             4.7, 14, 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=600'),
(32, 'Odaiba Marina',           '4-star hotel on the scenic Odaiba waterfront',                   '10-1 Odaiba, Tokyo',    '15:00', '11:00', 4, 175.00, 'JPY', 'Double,Suite',        'WiFi,Restaurant,AC,Gym',                   4.4, 21, 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=600'),
(32, 'Chiyoda Business Hotel',  '3-star hotel conveniently close to the Imperial Palace',        '11-1 Chiyoda, Tokyo',   '14:00', '10:00', 3,  80.00, 'JPY', 'Single,Double',       'WiFi,AC,TV',                               4.1, 25, 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=600'),
(32, 'Meguro Boutique',         '4-star boutique hotel in the quiet, leafy Meguro district',     '12-1 Meguro, Tokyo',    '15:00', '11:00', 4, 185.00, 'JPY', 'Double,Suite',        'WiFi,Restaurant,Gym,AC',                   4.6, 18, 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=600');

-- Bali hotels (destination_id = 34)
INSERT INTO hotels (destination_id, name, description, address, check_in_time, check_out_time, star_rating, price_per_night, currency, room_types, amenities, average_rating, available_rooms, image_url) VALUES
(34, 'Ubud Luxury Resort',       '5-star resort in Ubud with infinity pools overlooking rice terraces', 'Ubud, Bali',          '15:00', '11:00', 5, 150.00, 'IDR', 'Suite,Deluxe',  'WiFi,Pool,Gym,Restaurant,Spa',           4.9, 12, 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600'),
(34, 'Seminyak Beach Club',      '4-star beachfront hotel in trendy Seminyak',                          'Seminyak, Bali',      '15:00', '11:00', 4,  90.00, 'IDR', 'Double,Suite',  'WiFi,Pool,Restaurant,Beach Access',      4.6, 20, 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600'),
(34, 'Kuta Surfside',            '3-star budget hotel steps from Kuta Beach',                           'Kuta, Bali',          '14:00', '10:00', 3,  45.00, 'IDR', 'Single,Double', 'WiFi,AC',                                4.2, 26, 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600'),
(34, 'Canggu Terrace',           '4-star hotel in the hip Canggu surf and café district',               'Canggu, Bali',        '15:00', '11:00', 4,  85.00, 'IDR', 'Double,Suite',  'WiFi,Restaurant,AC,Gym',                 4.5, 22, 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600'),
(34, 'Sanur Marina',             '3-star hotel near the peaceful Sanur harbour',                        'Sanur, Bali',         '14:00', '10:00', 3,  55.00, 'IDR', 'Double,Suite',  'WiFi,AC,Restaurant',                     4.3, 24, 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600'),
(34, 'Denpasar Urban',           '2-star budget hotel in central Denpasar',                             'Denpasar, Bali',      '13:00', '10:00', 2,  35.00, 'IDR', 'Single,Double', 'WiFi',                                   3.8, 30, 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600'),
(34, 'Jimbaran Bay Resort',      '5-star luxury resort overlooking the beautiful Jimbaran Bay',         'Jimbaran, Bali',      '15:00', '11:00', 5, 180.00, 'IDR', 'Suite,Deluxe',  'WiFi,Pool,Gym,Restaurant,Spa,Beach',     4.8, 14, 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600'),
(34, 'Nusa Dua Palace',          '5-star resort in the exclusive Nusa Dua enclave',                     'Nusa Dua, Bali',      '15:00', '11:00', 5, 160.00, 'IDR', 'Suite,Deluxe',  'WiFi,Pool,Gym,Restaurant,Beach',         4.7, 16, 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600'),
(34, 'Uluwatu Cliffside',        '4-star hotel perched dramatically on the Uluwatu cliffs',             'Uluwatu, Bali',       '15:00', '11:00', 4,  95.00, 'IDR', 'Double,Suite',  'WiFi,Pool,Restaurant,Gym',               4.6, 19, 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600'),
(34, 'Petitenget Hideaway',      '3-star private villa-style hotel in Petitenget',                      'Petitenget, Bali',    '14:00', '10:00', 3,  65.00, 'IDR', 'Double,Suite',  'WiFi,AC,Restaurant',                     4.4, 23, 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600'),
(34, 'Seminyak Budget Hostel',   '2-star backpacker hostel in the heart of Seminyak',                   'Seminyak, Bali',      '13:00', '10:00', 2,  30.00, 'IDR', 'Single,Double', 'WiFi',                                   3.7, 32, 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600'),
(34, 'Tegallalang Green Resort', '4-star eco-resort set among the Tegallalang rice terraces',           'Tegallalang, Bali',   '15:00', '11:00', 4, 100.00, 'IDR', 'Double,Suite',  'WiFi,Pool,Restaurant,Eco-Friendly',      4.5, 20, 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600');

-- ============================================================
-- SAMPLE REVIEWS  (user_id = 1 = the auto-created admin)
-- ============================================================
INSERT INTO reviews (user_id, destination_id, hotel_id, rating, title, content, review_type, helpful_count) VALUES
(1, 31, 1,    5,   'Amazing Stay at Eiffel Tower Hotel',   'The hotel exceeded all my expectations. The location is perfect, the service is impeccable, and the rooms are luxurious. Highly recommended!', 'Hotel',       23),
(1, 31, 2,    4.5, 'Charming Boutique Hotel in Marais',    'Great location in the historic Marais district. The staff is very friendly and the room is clean and cozy. Would stay again!',                  'Hotel',       18),
(1, 31, NULL, 4.8, 'Paris is Magical',                     'Paris lived up to all the hype. The Eiffel Tower, the museums, the food — everything is incredible. A must-visit destination!',                  'Destination', 45),
(1, 32, NULL, 5,   'Tokyo is Unforgettable',               'This city is a perfect blend of tradition and modernity. The food is amazing, the culture is rich, and the people are so welcoming. Loved it!',  'Destination', 52),
(1, 34, NULL, 4.7, 'Paradise in Bali',                     'Bali is everything you dream of — beautiful beaches, friendly people, and amazing prices. The perfect vacation destination!',                     'Destination', 38);

-- ============================================================
-- UPDATE RATINGS
-- ============================================================
UPDATE destinations SET average_rating = 4.8, review_count = 1 WHERE destination_id = 31;
UPDATE destinations SET average_rating = 4.8, review_count = 1 WHERE destination_id = 32;
UPDATE destinations SET average_rating = 4.7, review_count = 1 WHERE destination_id = 34;

UPDATE hotels SET average_rating = 5,   review_count = 1 WHERE hotel_id = 1;
UPDATE hotels SET average_rating = 4.5, review_count = 1 WHERE hotel_id = 2;

COMMIT;
